baseURL = "/"
languageCode = "en-us"
title = "Michael Brenndoerfer"

theme = "hugo-steam-theme"
disqusShortname = "michael-brenndoerfer"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-96478221-1"
# Number of posts per page
paginate = 10

[params]
	title = "Michael Brenndoerfer"
	subtitle = "Machine Learning, Deep Learning, Statistics, Distributed Systems, Big Data & Finance"
	copyright = ""
	# You can choose between green, orange, red and blue.
	themecolor = "custom"
	
	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Michael Brenndoerfer"
	bio = "programmer - data guy - runs on coffee"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = "Camebridge, MA"
	twitter = "mbrenndoerfer"
	linkedin = "michaelbrenndoerfer"
	googleplus = ""
	facebook = "michael.brenndoerfer"
	instagram = "leanlive"
	github = "brenndoerfer"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Continue reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
